### ISSUE TITLE
Error when I clicked on login

### ISSUE THREAD

**Issue by vasuskimo** [miguelmota/alexa-voice-service.js#1]
python -m SimpleHTTPServer 9000
Serving HTTP on 0.0.0.0 port 9000 ...
127.0.0.1 - - [12/Apr/2016 22:23:40] "GET /example/ HTTP/1.1" 200 -
127.0.0.1 - - [12/Apr/2016 22:23:40] "GET /example/index.css HTTP/1.1" 200 -
127.0.0.1 - - [12/Apr/2016 22:23:40] "GET /example/index.bundle.js HTTP/1.1" 200 -
127.0.0.1 - - [12/Apr/2016 22:23:44] code 400, message Bad request syntax ('\x16\x03\x01\x00\xc2\x01\x00\x00\xbe\x03\x03!L\xd5s\x12\xd9\x862,\xf9{b\x0fF3\xbb\xccw\xbeq\xe7P/)\xd0d\x13\xc9?\\x1b\xa7\x00\x00\x1c\xc0+\xc0/\xcc\xa9\xcc\xa8\xcc\x14\xcc\x13\xc0')
127.0.0.1 - - [12/Apr/2016 22:23:44] "??!L?sن2,?{bF3??w?q?P/)?d??\?+?/̨̩???" 400 -
127.0.0.1 - - [12/Apr/2016 22:23:44] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x00\x99\x01\x00\x00\x95\x03\x02gJ')
127.0.0.1 - - [12/Apr/2016 22:23:44] "??gJ  19?}???\?-SP???N;qt???.,??" 400 -
127.0.0.1 - - [12/Apr/2016 22:23:44] code 400, message Bad request syntax ('\x16\x03\x01\x00\x99\x01\x00\x00\x95\x03\x01\xc2<5W,\xcd\x0f\xdb\xc4\xb0\xfa\x1d\xd8\x96\xc9\xdd\x9d\xb1\xcd\xfbW\xe5)\xffh\xf7\xbaaS\xe4\xbc\xa9\x00\x00\x10\xc0')
127.0.0.1 - - [12/Apr/2016 22:23:44] "???<5W,??İ?ؖ?ݝ???W?)?h??aS伩?" 400 -

**Comment by miguelmota** [comment]
Sorry those docs were outdated.

Go into `example/` directory and run:

``` bash
$ npm install
$ node server.js
```

Then navigate to 

``` bash
https://localhost:9745
```

**Comment by vasuskimo** [comment]
Works great. Thanks
