### ISSUE TITLE
Amazon returned error upon Authentication?

### ISSUE THREAD

**Issue by manojcena** [miguelmota/alexa-voice-service.js#11]
Hi i followed the mention steps in this repo and i created new product in amazon developer console and i took the client id of that product and i updated on the code. then click on login will navigate to the amazon page after entering all the required details it shows okay or cancel the click on okey it gives me the following error.

We're sorry!
An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly.

I searched in the net some of the links says need to mention the device details but i am unable to see the options as you mentioned in this link.

 https://miguelmota.com/blog/alexa-voice-service-authentication/

the options like device type and new device details because i need to pass the device id,serial number for amazon auth request.

please help me to solve this problem.

**Comment by E3V3A** [comment]
@manojcena @miguelmota 
Hi Please see [my post here](https://github.com/dolanmiu/MMM-awesome-alexa/issues/57#issuecomment-374205781). We might need to fix a bit on the request.
