### ISSUE TITLE
The response message is not played

### ISSUE THREAD

**Issue by sakirtemel** [miguelmota/alexa-voice-service.js#4]
When a response is received, the player wants to play that but it fails with this error:

```
Uncaught (in promise) null
```

I've debugged what was wrong with it, then I saw the problem was in here

https://github.com/miguelmota/alexa-voice-service.js/blob/master/lib/utils/arrayBufferToAudioBuffer.js#L15

and the function has been called from here

https://github.com/miguelmota/alexa-voice-service.js/blob/43158535bb9b89f8873aaf49863fbaa2e3e679e3/lib/Player.js#L67

since there weren't any reject function passed, it's only showing `Uncaught in promise` error. When I wanted to see the real error on the reject function after implementing it, it wasn't showing me the exact problem.

The response is downloadable, and when you download that you're able to play that file and it contains the correct answer.

**Comment by sakirtemel** [comment]
The issue was because I'm using Chromium, and Chromium does not support the codecs built-in.

**Comment by miguelmota** [comment]
@sakirtemel good looking out. Please don't hesitate to submit PRs for issues
